version: '3'
services:
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - '8083:8080'
    depends_on:
      - 'db'
    restart: always
    env_file: .env
    #environment:
            # HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
            #HASURA_GRAPHQL_ENABLE_CONSOLE: '${HASURA_GRAPHQL_ENABLE_CONSOLE}' # set to "false" to disable console
            #HASURA_GRAPHQL_ENABLED_LOG_TYPES: ${HASURA_GRAPHQL_ENABLED_LOG_TYPES}
            #HASURA_GRAPHQL_MIGRATIONS_DIR: ${HASURA_GRAPHQL_MIGRATIONS_DIR}
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  # postgres:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   volumes:
  #     - postgresvol:/var/lib/postgresql/data
  db:
    image: supabase/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    restart: always
    environment:
        - discovery.type=single-node
        - cluster.name=docker-cluster
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
  logstash:
    image: namdd72/logstash
    restart: always
    build: .
    depends_on:
        - db
        - elasticsearch
    volumes:
        - ./logstash-pipeline/:/usr/share/logstash/pipeline/


  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "asdf@asdf.com"
      PGADMIN_DEFAULT_PASSWORD: "asdf"
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8087:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  postgresvol:
  elasticsearch-data:
  pgadmin:
